[tool.ruff]

target-version = "py39"

extend-select = [
  "B",
  "C",
  "I",
  "W",
]

exclude = [
	"extensions",
	"extensions-disabled",
  "extensions-builtin",
  "modules/lora",
  "modules/lycoris",
  "modules/dml",
]

ignore = [
	"C408", # Rewrite as a literal
	"C901", # Function is too complex
	"E501", # Line too long
	"E731", # Do not assign a `lambda` expression, use a `def`
	"I001", # Import block is un-sorted or un-formatted
	"W605", # invalid escape sequence, messes with some docstrings
  "E402", # Module level import not at top of file
  "F401", # Imported but unused
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.security.HTTPBasic"]

[tool.pytest.ini_options]
base_url = "http://127.0.0.1:7860"
